twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    paths:
        'public/images/films': filmImage
        'public/images/users': userImage
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_4_layout.html.twig'