version: "3.9"

services:
  web:
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 start_with_request=yes
      PHP_IDE_CONFIG: serverName=MovieReview
    extra_hosts:
      - "host.docker.internal:host-gateway"
